apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-cluster

resources:
  - namespace.yaml
  - network-policy.yaml
  - resource-quota.yaml

labels:
  - pairs:
      app.kubernetes.io/name: redis-cluster
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: platform-tools
      managed-by: argocd
